#!/bin/bash

yellow='\033[33m'
red='\033[31m'
green='\033[32m'
reset='\033[0m'

# Get the last commit hash
last_commit=$(git rev-parse --short HEAD)

# Display success message with commit hash
echo "${green}Push successful! Last commit: $last_commit ${reset}"