#!/bin/bash

function prompt_continue_with_errors() {
  read -p "Do you want to continue with errors? (y/n) " -n 1 -r < /dev/tty
  echo ""
  if [[ ! $REPLY =~ ^[Yy]$ ]]; then
    exit 1
  fi
}

# Run flutter analyze
analysis_output=$(flutter analyze 2>&1)

# If there are any issues, prompt the user to continue
if [ $? -ne 0 ]; then
  echo "flutter analyze found issues:"
  echo "$analysis_output"
  prompt_continue_with_errors
fi

# Run flutter test
test_output=$(flutter test 2>&1)

# If there are any failures, prompt the user to continue
if [[ $test_output == *"Some tests failed"* ]]; then
  echo "flutter test failed:"
  echo "$test_output"
  prompt_continue_with_errors
fi
