#!/bin/sh

# Set the color variables
yellow='\033[33m'
reset='\033[0m'

branch_name=`git rev-parse --abbrev-ref HEAD`

num_of_commits="$(git rev-list --count HEAD ^${new_branch_name})"

if [[ $num_of_commits = 0 ]]
then
    if ! [[ $branch_name =~ $regexBranchName ]]; then
    echo $branch_name
    echo "${yellow}pre-push:${reset} Branch name must start with 'feature/AMT-', 'bugfix/AMT-', or 'hotfix/AMT-', followed by one or more digits.${reset}"
    exit 1
    fi
fi
