#!/bin/sh

COMMIT_MSG_FILE=$1
COMMIT_SOURCE=$2
SHA1=$3

# Set the color variables
yellow='\033[33m'
reset='\033[0m'

branchName=`git rev-parse --abbrev-ref HEAD`
commit_msg=$(cat $1)
regexStart='^(feat|feature|refactor|fix|docs): .*'
regexEnd='^.*\(AMT-[0-9]+\)$'


if [[ ! $commit_msg =~ $regexStart ]]; then
  echo "${yellow}pre-commit:${reset} Your commit message must start with some of these 'feature:' 'refactor:' 'fix:' 'docs:'${reset}"
  exit 1
fi
if [[ ! $commit_msg =~ $regexEnd ]]; then
  echo "${yellow}pre-commit:${reset} Your commit message must end with issue number for ex. (AMT-333)'${reset}"
  exit 1
fi
